routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('auth:admin')->group(function () {
    Route::prefix('admins')->as('admin.')->namespace('Admin')->group(function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::post('logout', 'Auth\LoginController@logout')->name('logout');
    });
});

Route::get('admins/login', 'Admin\Auth\LoginController@showLoginForm')->middleware('guest:admin')->name('admin.login');
Route::post('admins/login', 'Admin\Auth\LoginController@login')->middleware('guest:admin')->name('admin.login');

Route::get('/', 'HomeController@index')->name('dashboard');
Route::get('benefits', 'BenefitsController@index')->name('benefits');

//Route::get('sign-up', 'Auth\LoginController@showLoginForm')->name('sign_up');

Route::get('sign-up', 'Auth\RegisterController@showRegistrationForm')->name('sign_up');
Route::post('register', 'Auth\RegisterController@register')->name('registration');

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');

//Route::get('profile', 'UserController@profile')->middleware(['auth', 'verified'])->name('user.profile');
Route::get('connect', 'UserController@connect')->middleware(['auth', 'verified'])->name('user.connect');
Route::post('connect', 'UserController@applyConnect')->middleware(['auth', 'verified'])->name('user.connect');
Route::get('member', 'UserController@member')->middleware(['auth', 'verified'])->name('user.member');

Route::get('subcategory', 'UserController@getSubcategory')->middleware(['auth', 'verified'])->name('user.getSubcategory');

Route::get('success', 'PaymentController@successful');
Route::get('cancel', 'PaymentController@cancel');
Route::post('itn', 'PaymentController@itn');

Route::get('private-sector', 'UserController@privateSector')->middleware(['auth', 'verified'])->name('user.private_sector');
Route::post('private-sector', 'UserController@storePrivateSector')->middleware(['auth', 'verified'])->name('user.private_sector');
Route::get('goverment-sector', 'UserController@govermentSector')->middleware(['auth', 'verified'])->name('user.goverment_sector');
Route::post('goverment-sector', 'UserController@storeGovermentSector')->middleware(['auth', 'verified'])->name('user.goverment_sector');
Route::get('business-sector', 'UserController@businessSector')->middleware(['auth', 'verified'])->name('user.business_sector');
Route::post('business-sector', 'UserController@storeBusinessSector')->middleware(['auth', 'verified'])->name('user.business_sector');

Route::get('invite', 'UserController@invite')->middleware(['auth', 'verified'])->name('user.invite');

//Route::post('sign-up', 'LoginController@showLoginForm')->name('registration');
//Route::get('signgjh-up', 'LoginController@showLoginForm')->name('login');
Route::get('getConnected', 'GetConnectedController@index')->name('getConnected');

Route::get('purpose', 'PurposeController@index')->name('purpose');
Route::get('privacy', 'PrivacyController@index')->name('privacy');
Route::get('terms', 'TermsController@index')->name('terms');

resources/views/admin/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    @include('admin.layouts.header')
</head>
<body class="sidebar-fixed header-fixed">
<div class="page-wrapper">
    @include('admin.layouts.nav')

    <div class="main-container">
        @include('admin.layouts.sidebar')

        <div class="content">
            @yield('content')
        </div>
    </div>
</div>
@include('admin.layouts.scripts')
@yield('scripts')
</body>
</html>

resources/views/admin/layouts/header.blade.php
<meta charset="UTF-8">
<meta name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Anabel - DE</title>
<link rel="stylesheet" href="{{ asset('admin/vendor/simple-line-icons/css/simple-line-icons.css') }}">
<link rel="stylesheet" href="{{ asset('admin/vendor/font-awesome/css/fontawesome-all.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin/css/styles.css') }}">

resources/views/admin/layouts/nav.blade.php
<nav class="navbar page-header">
    <a href="#" class="btn btn-link sidebar-mobile-toggle d-md-none mr-auto">
        <i class="fa fa-bars"></i>
    </a>

    <a class="navbar-brand" href="#">
        Uber
    </a>

    <a href="#" class="btn btn-link sidebar-toggle d-md-down-none">
        <i class="fa fa-bars"></i>
    </a>

    <ul class="navbar-nav ml-auto">
        <li class="nav-item d-md-down-none">
            <a href="#">
                <i class="fa fa-bell"></i>
                <span class="badge badge-pill badge-danger">5</span>
            </a>
        </li>

        <li class="nav-item d-md-down-none">
            <a href="#">
                <i class="fa fa-envelope-open"></i>
                <span class="badge badge-pill badge-danger">5</span>
            </a>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
               aria-expanded="false">
                <img src="{{ asset('admin/imgs/avatar-1.png') }}" class="avatar avatar-sm" alt="logo">
                <span class="small ml-1 d-md-down-none">John Smith</span>
            </a>

            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-header">Account</div>

                <a href="#" class="dropdown-item">
                    <i class="fa fa-user"></i> Profile
                </a>

                <a href="#" class="dropdown-item">
                    <i class="fa fa-envelope"></i> Messages
                </a>

                <div class="dropdown-header">Settings</div>

                <a href="#" class="dropdown-item">
                    <i class="fa fa-bell"></i> Notifications
                </a>

                <a href="#" class="dropdown-item">
                    <i class="fa fa-wrench"></i> Settings
                </a>
                <a href="{{ route('admin.logout') }}" class="dropdown-item" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                    <i class="fa fa-lock"></i> {{ __('Logout') }}
                </a>
                <form id="logout-form" action="{{ route('admin.logout') }}" method="post"
                      style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/admin/layouts/scripts.blade.php
<script src="{{ asset('admin/vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('admin/vendor/popper.js/popper.min.js') }}"></script>
<script src="{{ asset('admin/vendor/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('admin/vendor/chart.js/chart.min.js') }}"></script>
<script src="{{ asset('admin/js/carbon.js') }}"></script>
<script src="{{ asset('admin/js/demo.js') }}"></script>

resources/views/admin/layouts/sidebar.blade.php
<div class="sidebar">
    <nav class="sidebar-nav">
        <ul class="nav">
            <li class="nav-title">Navigation</li>

            <li class="nav-item">
                <a href="{{ route('admin.dashboard') }}" class="nav-link active">
                    <i class="icon icon-speedometer"></i> Dashboard
                </a>
            </li>
        </ul>
    </nav>
</div>